export default {
  header: {
    navigationLabel: 'Navigation principale',
    menuToggleLabel: 'Ouvrir ou fermer le menu',
    themeToggleLabel: 'Basculer entre le mode sombre et le mode clair',
    rssFeedLabel: 'Flux RSS',
    event: 'Événement',
    cfp: 'CFP',
    venue: 'Lieu',
    team: 'Équipe',
    sponsors: 'Sponsors',
    tickets: 'Billetterie',
    program: 'Programme',
    sponsoring: 'Sponsoring',
    practicalInfo: 'Infos pratiques',
    about: 'À propos',
    contact: 'Contact',
    brandGuidelines: 'Charte graphique',
  },
  footer: {
    event: 'Événement',
    organization: 'Organisation',
    sponsoring: 'Sponsoring',
    program: 'Programme',
    practicalInfo: 'Infos pratiques',
    about: 'À propos',
    brandGuidelines: 'Charte graphique',
    contact: 'Contact',
    terms: 'Mentions légales',
    privacy: 'Politique de confidentialité',
    note: 'Conçu par la <a class="text-blue-600 underline dark:text-muted" href="https://cloudnative-provence.fr/">communauté Cloud Native Provence</a> · Tous droits réservés.',
    logoAlt: 'Logo Cloud Native Provence',
  },
} as const;
