const tracks = [
  { id: 'keynote', label: 'Keynotes & Community', accent: 'from-sky-500 to-cyan-400' },
  { id: 'platform', label: 'Platform Engineering', accent: 'from-emerald-500 to-lime-400' },
  { id: 'builders', label: 'Builders Track', accent: 'from-fuchsia-500 to-rose-400' },
] as const;

const rooms = [
  { id: 'auditorium', label: 'Grand Auditorium' },
  { id: 'luberon', label: 'Room Luberon' },
  { id: 'sainte-victoire', label: 'Room Sainte-Victoire' },
  { id: 'expo', label: 'Partner Expo' },
] as const;

const sessions = [
  {
    id: 'registration-breakfast',
    title: 'Registration & breakfast',
    description:
      'Pick up your badge, meet the first attendees of the day, and explore the partner expo with coffee and viennoiseries.',
    startsAtTime: '08:15',
    endsAtTime: '09:00',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Cloud Native Provence crew'],
    format: 'Community moment',
    isGlobal: true,
    tags: ['networking', 'expo'],
  },
  {
    id: 'opening-keynote',
    title: 'Opening keynote · Building the next cloud native chapter in Provence',
    description:
      'A high-energy opening keynote on the local ecosystem, community highlights, and the big ideas shaping this edition of KCD Provence.',
    startsAtTime: '09:00',
    endsAtTime: '09:40',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['auditorium'],
    speakers: ['Sherine Khoury', 'Frédéric Léger'],
    format: 'Keynote',
    isGlobal: true,
    tags: ['community', 'keynote'],
  },
  {
    id: 'platform-golden-paths',
    title: 'Golden paths that platform teams actually maintain',
    description:
      'Learn how to design paved roads that stay relevant over time, with governance, feedback loops, and pragmatic self-service guardrails.',
    startsAtTime: '09:55',
    endsAtTime: '10:25',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Julie Martin'],
    format: 'Talk · 30 min',
    tags: ['platform engineering', 'developer experience'],
  },
  {
    id: 'builders-gitops',
    title: 'GitOps beyond clusters: managing cloud resources safely',
    description:
      'A practical walkthrough of multi-environment GitOps workflows, including drift management, secret handling, and promotion strategies.',
    startsAtTime: '09:55',
    endsAtTime: '10:25',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Marco Bellini'],
    format: 'Talk · 30 min',
    tags: ['gitops', 'operations'],
  },
  {
    id: 'keynote-observability',
    title: 'Observability stories from teams running production at scale',
    description:
      'Real-world lessons on what teams monitor, how they investigate incidents faster, and where dashboards still fail the people who need them.',
    startsAtTime: '09:55',
    endsAtTime: '10:25',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Nora El Mansouri'],
    format: 'Talk · 30 min',
    tags: ['observability', 'sre'],
  },
  {
    id: 'coffee-break',
    title: 'Coffee break & partner expo',
    description: 'Refuel, continue the hallway track, and meet companies building the cloud native ecosystem.',
    startsAtTime: '10:25',
    endsAtTime: '10:55',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Partners & attendees'],
    format: 'Break',
    isGlobal: true,
    tags: ['break', 'expo'],
  },
  {
    id: 'keynote-ai-platforms',
    title: 'AI workloads on Kubernetes without platform chaos',
    description:
      'A keynote-style session on balancing GPU demand, cost, and developer ergonomics when AI teams join the platform.',
    startsAtTime: '10:55',
    endsAtTime: '11:25',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Thomas Perelle'],
    format: 'Talk · 30 min',
    tags: ['ai', 'kubernetes'],
  },
  {
    id: 'platform-scorecards',
    title: 'Internal platform scorecards that improve delivery',
    description:
      'See how to define service maturity, score operational readiness, and use scorecards to drive better adoption without bureaucracy.',
    startsAtTime: '10:55',
    endsAtTime: '11:25',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Émilien Escalle'],
    format: 'Talk · 30 min',
    tags: ['platform engineering', 'metrics'],
  },
  {
    id: 'builders-wasm',
    title: 'Fast experiments with WebAssembly on the edge',
    description:
      'From demos to production patterns, discover how teams use Wasm runtimes to move lightweight workloads closer to users.',
    startsAtTime: '10:55',
    endsAtTime: '11:25',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Henrik Rexed'],
    format: 'Talk · 30 min',
    tags: ['edge', 'wasm'],
  },
  {
    id: 'keynote-security',
    title: 'Security guardrails that teams do not work around',
    description:
      'A practical look at admission policies, supply-chain controls, and security defaults that help instead of block delivery.',
    startsAtTime: '11:35',
    endsAtTime: '12:05',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Donia Chaiehloudj'],
    format: 'Talk · 30 min',
    tags: ['security', 'supply chain'],
  },
  {
    id: 'platform-finops',
    title: 'FinOps feedback loops for shared platforms',
    description:
      'Give application teams the cost signals they need by combining chargeback-ready data, product thinking, and lightweight automation.',
    startsAtTime: '11:35',
    endsAtTime: '12:05',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Rémi Verchère'],
    format: 'Talk · 30 min',
    tags: ['finops', 'platform engineering'],
  },
  {
    id: 'builders-service-mesh',
    title: 'Service mesh lessons after the honeymoon phase',
    description:
      'An honest session about what teams keep, what they simplify, and what they retire after years of service mesh operations.',
    startsAtTime: '11:35',
    endsAtTime: '12:05',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Luc Juggery'],
    format: 'Talk · 30 min',
    tags: ['networking', 'operations'],
  },
  {
    id: 'lunch',
    title: 'Lunch, demos & community booths',
    description:
      'A long networking break to grab lunch, discover partner demos, and keep conversations going with the community.',
    startsAtTime: '12:05',
    endsAtTime: '13:25',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Partners & community booths'],
    format: 'Break',
    isGlobal: true,
    tags: ['lunch', 'networking'],
  },
  {
    id: 'keynote-case-study',
    title: 'From migration to momentum: a cloud native case study',
    description:
      'A candid story about migration trade-offs, what the team automated, and what they deliberately left simple to move faster.',
    startsAtTime: '13:25',
    endsAtTime: '13:55',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Sébastien Blanc'],
    format: 'Talk · 30 min',
    tags: ['case study', 'migration'],
  },
  {
    id: 'platform-idp',
    title: 'Designing an internal developer portal people return to',
    description:
      'Move from a catalog nobody opens to a portal that shortens onboarding, exposes workflows, and supports platform product discovery.',
    startsAtTime: '13:25',
    endsAtTime: '13:55',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Camille Bernard'],
    format: 'Talk · 30 min',
    tags: ['developer portal', 'platform engineering'],
  },
  {
    id: 'builders-debugging',
    title: 'Debugging distributed systems without losing the room',
    description:
      'A story-driven session about tracing failures across queues, services, and infrastructure layers while keeping incident response collaborative.',
    startsAtTime: '13:25',
    endsAtTime: '13:55',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Amina Saidi'],
    format: 'Talk · 30 min',
    tags: ['debugging', 'distributed systems'],
  },
  {
    id: 'lightning-talks',
    title: 'Lightning talks · five ideas in twenty minutes',
    description:
      'A fast-paced shared slot with short talks on testing, DORA metrics, policy as code, green software, and platform culture.',
    startsAtTime: '14:05',
    endsAtTime: '14:30',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['auditorium'],
    speakers: ['Multiple speakers'],
    format: 'Lightning talks',
    isGlobal: true,
    tags: ['lightning talks', 'community'],
  },
  {
    id: 'afternoon-break',
    title: 'Afternoon break',
    description:
      'Grab a coffee, compare notes with other attendees, and make your final plan for the last sessions of the day.',
    startsAtTime: '14:30',
    endsAtTime: '15:00',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Community space'],
    format: 'Break',
    isGlobal: true,
    tags: ['break', 'networking'],
  },
  {
    id: 'keynote-closing',
    title: 'Closing keynote · What resilient teams do differently',
    description:
      'A closing keynote on operating with confidence: clear ownership, healthy escalation paths, and continuous learning in fast-moving systems.',
    startsAtTime: '15:00',
    endsAtTime: '15:35',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Mélanie Fontaine'],
    format: 'Keynote',
    tags: ['resilience', 'teamwork'],
  },
  {
    id: 'platform-roadmaps',
    title: 'Roadmapping a platform product with real user feedback',
    description:
      'Translate platform adoption signals, friction points, and support requests into a roadmap that teams trust.',
    startsAtTime: '15:00',
    endsAtTime: '15:35',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Anaïs Roux'],
    format: 'Talk · 30 min',
    tags: ['product thinking', 'platform engineering'],
  },
  {
    id: 'builders-runtimes',
    title: 'Choosing the right runtime for modern workloads',
    description:
      'Containers, functions, edge runtimes, Wasm: compare trade-offs for startup time, portability, and operational complexity.',
    startsAtTime: '15:00',
    endsAtTime: '15:35',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Karim Benaissa'],
    format: 'Talk · 30 min',
    tags: ['containers', 'serverless'],
  },
  {
    id: 'closing-party',
    title: 'Closing remarks & apéro',
    description:
      'Wrap up the day with final thanks, a few surprises, and a relaxed apéro with speakers, volunteers, and partners.',
    startsAtTime: '16:00',
    endsAtTime: '18:00',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Cloud Native Provence crew'],
    format: 'Community moment',
    isGlobal: true,
    tags: ['afterparty', 'networking'],
  },
] as const;

export default {
  tracks,
  rooms,
  sessions,
} as const;
