const tracks = [
  { id: 'keynote', label: 'Keynotes & communauté', accent: 'from-sky-500 to-cyan-400' },
  { id: 'platform', label: 'Platform Engineering', accent: 'from-emerald-500 to-lime-400' },
  { id: 'builders', label: 'Développement', accent: 'from-fuchsia-500 to-rose-400' },
] as const;

const rooms = [
  { id: 'auditorium', label: 'Grand Auditorium' },
  { id: 'luberon', label: 'Salle Luberon' },
  { id: 'sainte-victoire', label: 'Salle Sainte-Victoire' },
  { id: 'expo', label: 'Espace partenaires' },
] as const;

const sessions = [
  {
    id: 'registration-breakfast',
    title: 'Accueil & petit-déjeuner',
    description:
      "Récupérez votre badge, rencontrez les premiers participants de la journée et découvrez l'espace partenaires autour d'un café.",
    startsAtTime: '08:15',
    endsAtTime: '09:00',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Équipe Cloud Native Provence'],
    format: 'Moment convivial',
    isGlobal: true,
    tags: ['networking', 'expo'],
  },
  {
    id: 'opening-keynote',
    title: "Keynote d'ouverture · Construire le prochain chapitre cloud native en Provence",
    description:
      "Une keynote d'ouverture sur la dynamique locale, les temps forts de la communauté et les grands sujets qui marquent cette édition de KCD Provence.",
    startsAtTime: '09:00',
    endsAtTime: '09:40',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['auditorium'],
    speakers: ['Sherine Khoury', 'Frédéric Léger'],
    format: 'Keynote',
    isGlobal: true,
    tags: ['communauté', 'keynote'],
  },
  {
    id: 'platform-golden-paths',
    title: 'Des golden paths que les équipes plateforme arrivent vraiment à maintenir',
    description:
      'Comment concevoir des parcours balisés qui restent utiles dans le temps, avec une gouvernance, des retours utilisateurs et des garde-fous pragmatiques.',
    startsAtTime: '09:55',
    endsAtTime: '10:25',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Julie Martin'],
    format: 'Conférence · 30 min',
    tags: ['platform engineering', 'developer experience'],
  },
  {
    id: 'builders-gitops',
    title: 'Le GitOps au-delà des clusters : piloter ses ressources cloud proprement',
    description:
      "Un tour d'horizon concret des workflows GitOps multi-environnements, de la gestion de la dérive jusqu'aux stratégies de promotion.",
    startsAtTime: '09:55',
    endsAtTime: '10:25',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Marco Bellini'],
    format: 'Conférence · 30 min',
    tags: ['gitops', 'ops'],
  },
  {
    id: 'keynote-observability',
    title: "Observabilité : histoires vécues d'équipes qui opèrent à grande échelle",
    description:
      'Des retours de terrain sur ce que les équipes surveillent, la façon dont elles analysent les incidents plus vite et les limites des tableaux de bord.',
    startsAtTime: '09:55',
    endsAtTime: '10:25',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Nora El Mansouri'],
    format: 'Conférence · 30 min',
    tags: ['observability', 'sre'],
  },
  {
    id: 'coffee-break',
    title: 'Pause café & espace partenaires',
    description:
      "Rechargez les batteries, poursuivez la discussion dans les couloirs et rencontrez les acteurs de l'écosystème cloud native.",
    startsAtTime: '10:25',
    endsAtTime: '10:55',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Partenaires & participants'],
    format: 'Pause',
    isGlobal: true,
    tags: ['pause', 'expo'],
  },
  {
    id: 'keynote-ai-platforms',
    title: 'Des workloads IA sur Kubernetes sans mettre la plateforme en vrac',
    description:
      "Une session sur l'équilibre entre besoins GPU, coûts et ergonomie développeur quand les équipes IA rejoignent la plateforme.",
    startsAtTime: '10:55',
    endsAtTime: '11:25',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Thomas Perelle'],
    format: 'Conférence · 30 min',
    tags: ['ia', 'kubernetes'],
  },
  {
    id: 'platform-scorecards',
    title: 'Des scorecards de plateforme qui améliorent vraiment la livraison logicielle',
    description:
      "Définir la maturité d'un service, évaluer sa préparation opérationnelle et utiliser ces scorecards pour guider l'adoption sans bureaucratie.",
    startsAtTime: '10:55',
    endsAtTime: '11:25',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Émilien Escalle'],
    format: 'Conférence · 30 min',
    tags: ['platform engineering', 'metrics'],
  },
  {
    id: 'builders-wasm',
    title: "Expérimenter vite avec WebAssembly à l'edge",
    description:
      "Des premiers prototypes jusqu'aux patterns de production : comment les équipes utilisent les runtimes Wasm au plus près des utilisateurs.",
    startsAtTime: '10:55',
    endsAtTime: '11:25',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Henrik Rexed'],
    format: 'Conférence · 30 min',
    tags: ['edge', 'wasm'],
  },
  {
    id: 'keynote-security',
    title: "Des garde-fous de sécurité que les équipes n'essaient pas de contourner",
    description:
      "Une approche concrète des politiques d'admission, des contrôles de la chaîne d'approvisionnement logicielle et des réglages par défaut qui facilitent la livraison logicielle.",
    startsAtTime: '11:35',
    endsAtTime: '12:05',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Donia Chaiehloudj'],
    format: 'Conférence · 30 min',
    tags: ['security', 'supply chain'],
  },
  {
    id: 'platform-finops',
    title: "Des boucles de retour d'information FinOps pour les plateformes partagées",
    description:
      'Donner les bons signaux de coût aux équipes applicatives grâce à des données exploitables, une approche produit et une automatisation légère.',
    startsAtTime: '11:35',
    endsAtTime: '12:05',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Rémi Verchère'],
    format: 'Conférence · 30 min',
    tags: ['finops', 'platform engineering'],
  },
  {
    id: 'builders-service-mesh',
    title: 'Le service mesh après la lune de miel',
    description:
      "Une session sans filtre sur ce que les équipes gardent, simplifient ou abandonnent après plusieurs années d'exploitation.",
    startsAtTime: '11:35',
    endsAtTime: '12:05',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Luc Juggery'],
    format: 'Conférence · 30 min',
    tags: ['networking', 'ops'],
  },
  {
    id: 'lunch',
    title: 'Déjeuner, démos & stands de la communauté',
    description:
      'Une longue pause pour déjeuner, découvrir les démos partenaires et continuer les échanges avec la communauté.',
    startsAtTime: '12:05',
    endsAtTime: '13:25',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Partenaires & stands de la communauté'],
    format: 'Pause',
    isGlobal: true,
    tags: ['déjeuner', 'networking'],
  },
  {
    id: 'keynote-case-study',
    title: "De la migration à l'élan : un retour d'expérience cloud native",
    description:
      "Un retour sans filtre sur les compromis d'une migration, ce que l'équipe a automatisé et ce qu'elle a volontairement gardé simple.",
    startsAtTime: '13:25',
    endsAtTime: '13:55',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Sébastien Blanc'],
    format: 'Conférence · 30 min',
    tags: ["retour d'expérience", 'migration'],
  },
  {
    id: 'platform-idp',
    title: 'Concevoir un portail développeur interne auquel on revient',
    description:
      "Passer d'un simple catalogue à un portail qui accélère l'intégration, présente les workflows et aide à découvrir la plateforme.",
    startsAtTime: '13:25',
    endsAtTime: '13:55',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Camille Bernard'],
    format: 'Conférence · 30 min',
    tags: ['developer portal', 'platform engineering'],
  },
  {
    id: 'builders-debugging',
    title: 'Déboguer des systèmes distribués sans perdre le fil en équipe',
    description:
      "Une session narrative sur le diagnostic d'incidents dans les files d'attente, les services et l'infrastructure, tout en préservant une gestion collective des incidents.",
    startsAtTime: '13:25',
    endsAtTime: '13:55',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Amina Saidi'],
    format: 'Conférence · 30 min',
    tags: ['debugging', 'distributed systems'],
  },
  {
    id: 'lightning-talks',
    title: 'Lightning talks · cinq idées en vingt minutes',
    description:
      'Un créneau très rythmé avec de courtes présentations sur les tests, les métriques DORA, la policy as code, le green software et la culture plateforme.',
    startsAtTime: '14:05',
    endsAtTime: '14:30',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['auditorium'],
    speakers: ['Plusieurs intervenants'],
    format: 'Lightning talks',
    isGlobal: true,
    tags: ['lightning talks', 'communauté'],
  },
  {
    id: 'afternoon-break',
    title: "Pause de l'après-midi",
    description:
      "Prenez un café, comparez vos notes avec d'autres participants et préparez vos derniers choix pour la fin de journée.",
    startsAtTime: '14:30',
    endsAtTime: '15:00',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Espace communauté'],
    format: 'Pause',
    isGlobal: true,
    tags: ['pause', 'networking'],
  },
  {
    id: 'keynote-closing',
    title: 'Keynote de clôture · Ce que font différemment les équipes résilientes',
    description:
      "Une keynote de clôture sur l'exploitation sereine : responsabilités claires, procédures d'escalade adaptées et apprentissage continu dans des systèmes en évolution rapide.",
    startsAtTime: '15:00',
    endsAtTime: '15:35',
    trackIds: ['keynote'],
    roomIds: ['auditorium'],
    speakers: ['Mélanie Fontaine'],
    format: 'Keynote',
    tags: ['résilience', 'équipes'],
  },
  {
    id: 'platform-roadmaps',
    title: "Définir la feuille de route d'une plateforme produit avec de vrais retours utilisateurs",
    description:
      "Transformer les signaux d'adoption, les points de friction et les demandes d'assistance en une feuille de route lisible et crédible.",
    startsAtTime: '15:00',
    endsAtTime: '15:35',
    trackIds: ['platform'],
    roomIds: ['luberon'],
    speakers: ['Anaïs Roux'],
    format: 'Conférence · 30 min',
    tags: ['product thinking', 'platform engineering'],
  },
  {
    id: 'builders-runtimes',
    title: 'Choisir le bon runtime pour les workloads modernes',
    description:
      "Conteneurs, fonctions, runtimes à l'edge, Wasm : comparez les compromis en matière de temps de démarrage, de portabilité et de complexité opérationnelle.",
    startsAtTime: '15:00',
    endsAtTime: '15:35',
    trackIds: ['builders'],
    roomIds: ['sainte-victoire'],
    speakers: ['Karim Benaissa'],
    format: 'Conférence · 30 min',
    tags: ['containers', 'serverless'],
  },
  {
    id: 'closing-party',
    title: 'Mot de fin & apéro',
    description:
      'On clôture la journée avec quelques surprises, des remerciements et un apéro détendu avec les intervenants, les bénévoles et les partenaires.',
    startsAtTime: '16:00',
    endsAtTime: '18:00',
    trackIds: ['keynote', 'platform', 'builders'],
    roomIds: ['expo'],
    speakers: ['Équipe Cloud Native Provence'],
    format: 'Moment convivial',
    isGlobal: true,
    tags: ['afterparty', 'networking'],
  },
] as const;

export default {
  tracks,
  rooms,
  sessions,
} as const;
