import { eventMeta, getEventPlace, getVenueInfo } from '~/domains/event/config/event';
import type { PracticalInfoTopicData } from '~/domains/pages/practical-info/model/content';

const venuePlace = getEventPlace('en');
const venueInfo = getVenueInfo('en');
const hasVenue = venuePlace.trim().length > 0;
const accommodationAreaLabel = hasVenue
  ? `near ${venuePlace} or in the city center`
  : `near ${eventMeta.city} city center`;
const accommodationResources = {
  tourismOffice: 'https://www.aixenprovencetourism.com/en/',
  maps: 'https://www.aixenprovencetourism.com/en/plan-your-trip/aix-maps/',
} as const;
const venueAddress = venueInfo.address;
const venueMapHref = venueInfo.mapUrl;
const venueAreaTitle = hasVenue ? `Around ${venuePlace}` : 'Around the venue';
const mapsSearchContextLabel = hasVenue ? venuePlace : eventMeta.city;
const mapsSearchAnchor = [venuePlace, venueAddress ?? eventMeta.city].filter(Boolean).join(', ');
const mapsSearchBaseQuery = hasVenue ? `accommodation near ${mapsSearchAnchor}` : `accommodation ${eventMeta.city}`;
const zoneSearchQueryById = {
  'venue-area': undefined,
  'near-stations': `${eventMeta.city} train station bus station`,
  'historic-center': `historic center ${eventMeta.city}`,
} as const;

const mapsPin = (lat: string, lon: string) => `https://www.google.com/maps?q=${lat},${lon}`;

export default {
  metadata: {
    title: 'Accommodation',
    description: `Find accommodation options in ${eventMeta.city} ${accommodationAreaLabel}.`,
  },
  tagline: 'Practical information',
  title: 'Accommodation',
  summary: `Find hotels, aparthotels, guesthouses, and short-term rentals ${accommodationAreaLabel}.`,
  content: `<p>Booking near the venue or the historic center early gives you the most choice. If you extend your stay, both make a great base for exploring Provence.</p>`,
  icon: 'tabler:bed',
  callToActionLabel: 'See accommodation details',
  backToOverviewLabel: 'Back to practical information',
  accommodationGuide: {
    heroTitle: 'Where to stay for an easy event day',
    heroIntro:
      'Pick an area that fits your arrival and how much you want to walk, then choose the lodging style that matches your trip.',
    areasTitle: 'Choose your base area first',
    areasIntro:
      'Three simple options depending on whether you want the shortest commute, the liveliest evenings, or a stress-free late arrival.',
    areas: [
      {
        title: venueAreaTitle,
        badge: 'Shortest event-day commute',
        description: 'The simplest morning, and easy to pop back between sessions.',
        commute: 'Book early - this zone fills first.',
      },
      {
        title: 'Historic center',
        badge: 'Best for food and evenings',
        description: 'Restaurants, cafes, and strolls at your door, and easy without a car.',
        commute: 'A short walk or taxi to the venue.',
      },
      {
        title: 'Edge of center',
        badge: 'Best for late arrivals',
        description: 'Simpler check-in and parking if you arrive late or leave early.',
        commute: 'Check the morning route to the venue before booking.',
      },
    ],
    stayTypesTitle: 'Match the lodging style to your trip',
    stayTypesIntro: 'The best choice fits your schedule, not the longest amenity list.',
    stayTypes: [
      {
        title: 'Hotels',
        badge: 'Simplest choice',
        description: 'Predictable service, luggage storage, and easy same-day arrivals.',
        bestFor: 'Short or solo stays',
      },
      {
        title: 'Aparthotels',
        badge: 'More space',
        description: 'A kitchenette and room to spread out for multi-night stays.',
        bestFor: 'Teams and longer stays',
      },
      {
        title: 'Guesthouses & rentals',
        badge: 'Most local',
        description: 'More charm and flexibility, with a bit more to check on access.',
        bestFor: 'Extended or group stays',
      },
    ],
    stayFinder: {
      title: 'Find your stay',
      intro:
        'Pick the zone, lodging type, and practical features that matter to you to narrow the curated list, then open a place to explore further.',
      filters: [
        {
          id: 'zone',
          label: 'Zone',
          options: [
            { id: 'venue-area', label: 'Venue area', searchQuery: zoneSearchQueryById['venue-area'] },
            { id: 'near-stations', label: 'Near stations', searchQuery: zoneSearchQueryById['near-stations'] },
            { id: 'historic-center', label: 'Historic center', searchQuery: zoneSearchQueryById['historic-center'] },
          ],
        },
        {
          id: 'type',
          label: 'Type',
          options: [
            { id: 'hotel', label: 'Hotel', searchQuery: 'hotel' },
            { id: 'aparthotel', label: 'Aparthotel', searchQuery: 'aparthotel' },
            { id: 'guesthouse', label: 'Guesthouse', searchQuery: 'guesthouse' },
          ],
        },
        {
          id: 'feature',
          label: 'Features',
          options: [{ id: 'parking', label: 'Parking', searchQuery: 'parking' }],
        },
      ],
      resultsLabel: 'stays match',
      mapsSearchLabel: 'See more on Google Maps',
      mapsSearchContextLabel,
      mapsSearchBaseQuery,
      venueMapHref,
      resetLabel: 'Reset filters',
      emptyTitle: 'No stay matches these criteria',
      emptyText: 'Try removing a filter to widen the options.',
      stays: [
        {
          name: 'Odalys City Aix-en-Provence',
          blurb: 'Apartment-style studios by cours Gambetta, steps from the congress centre, with on-site parking.',
          address: '15 cours Gambetta, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Venue area',
          typeId: 'aparthotel',
          typeLabel: 'Aparthotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.odalys-vacances.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.52419', '5.454989'),
        },
        {
          name: 'Hotel Cardinal',
          blurb: 'Characterful, good-value hotel in a pair of 18th-century houses in the Mazarin quarter.',
          address: '24 rue Cardinale, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Venue area',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: [],
          websiteLabel: 'Website',
          websiteHref: 'https://www.hotel-cardinal-aix.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.525482', '5.451718'),
        },
        {
          name: 'Villa Saint-Ange',
          blurb: 'Five-star bastide domain a short walk from the venue, with a covered, secure car park.',
          address: '7 traverse Saint-Pierre, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Venue area',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.villasaintange.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.523472', '5.458015'),
        },
        {
          name: 'Hotel des Arts',
          blurb: 'Simple, friendly two-star a few minutes from the venue, cours Mirabeau, and La Rotonde.',
          address: '3 rue de la Fonderie, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Venue area',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: [],
          websiteLabel: 'Website',
          websiteHref: 'https://hoteldesarts-aix.fr/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.529323', '5.453524'),
        },
        {
          name: 'Villa Gallici',
          blurb: 'Five-star Relais & Chateaux bastide with gardens and private parking, a short ride from the venue.',
          address: '18 avenue de la Violette, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Venue area',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.villagallici.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.536411', '5.448629'),
        },
        {
          name: 'La petite Mazarine',
          blurb: 'Peaceful two-room guesthouse with a shared pool in the hills, a few minutes from the centre by car.',
          address: '1135 chemin du vallon des lauriers, 13080 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Venue area',
          typeId: 'guesthouse',
          typeLabel: 'Guesthouse',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.aixenprovencetourism.com/fr/fiche/la-petite-mazarine-7579730',
          mapLabel: 'Map',
          mapHref: mapsPin('43.545628', '5.471568'),
        },
        {
          name: 'Hotel Rotonde',
          blurb: 'Elegant four-star right by La Rotonde, next to the bus and train stations, with private parking.',
          address: '15 avenue des Belges, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.hotel-rotonde.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.523677', '5.442665'),
        },
        {
          name: 'Sejours et Affairs Mirabeau',
          blurb: 'Ready-to-live studios and one-bedroom flats by the stations, with covered private parking.',
          address: '615 avenue Wolfgang Amadeus Mozart, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'aparthotel',
          typeLabel: 'Aparthotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref:
            'https://www.myresidhome.com/aix-en-provence/sejours-affaires-aix-en-provence-mirabeau/apparthotel-residence-hoteliere.html',
          mapLabel: 'Map',
          mapHref: mapsPin('43.525363', '5.441426'),
        },
        {
          name: 'Boutique Hotel Cezanne',
          blurb: 'Design boutique hotel a step from the stations, with private parking on request.',
          address: '40 avenue Victor Hugo, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://boutiquehotelcezanne.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.523353', '5.445922'),
        },
        {
          name: 'Odalys City Aix-en-Provence Centre Rotonde',
          blurb: 'Four-star aparthotel steps from La Rotonde, with an underground garage and a pool.',
          address: '24 boulevard Albert Charrier, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'aparthotel',
          typeLabel: 'Aparthotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.odalys-vacances.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.521542', '5.444778'),
        },
        {
          name: 'Hotel Saint-Christophe',
          blurb: 'Classic Provencal address near La Rotonde and the stations, with a garage and nearby parking.',
          address: '2 avenue Victor Hugo, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.hotel-saintchristophe.fr/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.525508', '5.446202'),
        },
        {
          name: 'Grand Hotel Roi Rene - MGallery',
          blurb: 'Upscale hotel between the stations and cours Mirabeau, with private parking on request.',
          address: '24 boulevard du Roi Rene, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.grandhotelroirene-aixenprovence.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.523875', '5.449543'),
        },
        {
          name: 'Aparthotel Adagio Aix Centre',
          blurb: 'Fully-equipped apartments near La Rotonde, renovated in 2025, with covered private parking.',
          address: '3-5 rue des Chartreux, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'aparthotel',
          typeLabel: 'Aparthotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.adagio-city.com/fr/hotel-6796-aparthotel-adagio-aix-en-provence-centre/index.shtml',
          mapLabel: 'Map',
          mapHref: mapsPin('43.529232', '5.440832'),
        },
        {
          name: 'Hotel Le Pigonnet',
          blurb:
            'Five-star garden retreat just south of the centre, with free private parking and easy station access.',
          address: '5 avenue du Pigonnet, 13090 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.esprit-de-france.com/fr/hotels/hotel-le-pigonnet',
          mapLabel: 'Map',
          mapHref: mapsPin('43.517891', '5.442081'),
        },
        {
          name: 'Villa des Felibres',
          blurb: 'Charming guesthouse with a pool and garage in a quiet street, a walk from the stations and centre.',
          address: '4 avenue Saint-Michel du Pigonnet, 13090 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Near stations',
          typeId: 'guesthouse',
          typeLabel: 'Guesthouse',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.aix-villa-felibres.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.516513', '5.441748'),
        },
        {
          name: 'Hotel des Augustins',
          blurb:
            'Characterful mid-range hotel in a former convent, steps from cours Mirabeau in the pedestrian centre.',
          address: '3 rue de la Masse, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Historic center',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: [],
          websiteLabel: 'Website',
          websiteHref: 'https://hotel-augustins.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.526913', '5.44714'),
        },
        {
          name: 'Negrecoste Hotel & Spa',
          blurb: 'Four-star hotel right on cours Mirabeau, with a Nuxe spa and private parking on request.',
          address: '33 cours Mirabeau, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Historic center',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://hotelnegrecoste.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.526768', '5.44896'),
        },
        {
          name: 'Hotel des Quatre Dauphins',
          blurb: 'Cosy hotel in a 19th-century mansion in Mazarin, moments from the Four Dolphins fountain.',
          address: '54 rue Roux Alpheran, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Historic center',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: [],
          websiteLabel: 'Website',
          websiteHref: 'https://lesquatredauphins.fr/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.524955', '5.450308'),
        },
        {
          name: "La Maison d'Aix",
          blurb: 'Intimate boutique guesthouse in a private mansion in the quiet Mazarin district.',
          address: '25 rue du 4 Septembre, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Historic center',
          typeId: 'guesthouse',
          typeLabel: 'Guesthouse',
          featureIds: [],
          websiteLabel: 'Website',
          websiteHref: 'https://www.lamaisondaix.com/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.524648', '5.450391'),
        },
        {
          name: 'Aquabella Hotel & Spa',
          blurb: 'Old-town calm with a garden and sensory spa near the Thermes, with parking nearby.',
          address: '2 rue des Etuves, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Historic center',
          typeId: 'hotel',
          typeLabel: 'Hotel',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.aquabella.fr/',
          mapLabel: 'Map',
          mapHref: mapsPin('43.531199', '5.44503'),
        },
        {
          name: 'Villa Helene',
          blurb: "Elegant five-room guesthouse with a pool and table d'hote on the leafy northern outskirts.",
          address: '920 chemin du Vallon de Bagnol, 13090 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Historic center',
          typeId: 'guesthouse',
          typeLabel: 'Guesthouse',
          featureIds: ['parking'],
          websiteLabel: 'Website',
          websiteHref: 'https://www.aixenprovencetourism.com/fr/fiche/villa-helene-7337018',
          mapLabel: 'Map',
          mapHref: mapsPin('43.544369', '5.434174'),
        },
      ],
    },
    checklistTitle: 'Before you book',
    checklist: [
      'Book early for the venue area or historic center.',
      'Check the real walking time to the venue, not just the area name.',
      'Arriving late? Confirm check-in hours and taxi access.',
      'Driving? Check parking before a central stay.',
    ],
    resourcesTitle: 'Useful links',
    resources: [
      { text: 'Aix-en-Provence tourism office', href: accommodationResources.tourismOffice },
      { text: 'City maps', href: accommodationResources.maps },
      { text: 'Venue website', href: venueInfo.url ?? 'https://www.aixenprovence-congres.com/en/' },
    ],
    notesTitle: 'Good to know',
  },
} satisfies PracticalInfoTopicData;
