import { eventMeta, getEventPlace, getVenueInfo } from '~/domains/event/config/event';
import type { PracticalInfoTopicData } from '~/domains/pages/practical-info/model/content';

const venuePlace = getEventPlace('fr');
const venueInfo = getVenueInfo('fr');
const hasVenue = venuePlace.trim().length > 0;
const accommodationAreaLabel = hasVenue
  ? `près du ${venuePlace} ou dans le centre-ville`
  : `près du centre-ville d'${eventMeta.city}`;
const accommodationResources = {
  tourismOffice: 'https://www.aixenprovencetourism.com/',
  maps: 'https://www.aixenprovencetourism.com/preparer-son-sejour/aix-plans/',
} as const;
const venueAddress = venueInfo.address;
const venueMapHref = venueInfo.mapUrl;
const venueAreaTitle = hasVenue ? `Autour du ${venuePlace}` : 'Autour du lieu';
const mapsSearchContextLabel = hasVenue ? venuePlace : eventMeta.city;
const mapsSearchAnchor = [venuePlace, venueAddress ?? eventMeta.city].filter(Boolean).join(', ');
const mapsSearchBaseQuery = hasVenue ? `hébergement près de ${mapsSearchAnchor}` : `hébergement ${eventMeta.city}`;
const zoneSearchQueryById = {
  'venue-area': undefined,
  'near-stations': `gare SNCF gare routière ${eventMeta.city}`,
  'historic-center': `centre historique ${eventMeta.city}`,
} as const;

const mapsPin = (lat: string, lon: string) => `https://www.google.com/maps?q=${lat},${lon}`;

export default {
  metadata: {
    title: 'Hébergement',
    description: `Trouvez où loger à ${eventMeta.city} ${accommodationAreaLabel}.`,
  },
  tagline: 'Infos pratiques',
  title: 'Hébergement',
  summary: `Trouvez des hôtels, appart-hôtels, maisons d'hôtes et locations courte durée ${accommodationAreaLabel}.`,
  content: `<p>Réserver tôt près du lieu ou du centre historique offre le plus de choix. Si vous prolongez, les deux sont une base idéale pour explorer la Provence.</p>`,
  icon: 'tabler:bed',
  callToActionLabel: "Voir les détails d'hébergement",
  backToOverviewLabel: 'Retour aux infos pratiques',
  accommodationGuide: {
    heroTitle: 'Où loger pour une journée sans stress',
    heroIntro:
      "Choisissez une zone selon votre arrivée et l'envie de marcher, puis le type d'hébergement adapté à votre séjour.",
    areasTitle: "Choisissez d'abord votre zone",
    areasIntro:
      'Trois options simples selon votre priorité : trajet le plus court, soirées animées, ou arrivée tardive sans stress.',
    areas: [
      {
        title: venueAreaTitle,
        badge: 'Trajet le plus court le jour J',
        description: 'Le matin le plus simple, et facile pour revenir entre les sessions.',
        commute: 'Réservez tôt - cette zone se remplit en premier.',
      },
      {
        title: 'Centre historique',
        badge: 'Idéal pour les restaurants et les soirées',
        description: 'Restaurants, cafés et balades au pied de la porte, et pratique sans voiture.',
        commute: "Une courte marche ou un taxi jusqu'au lieu.",
      },
      {
        title: 'En lisière du centre',
        badge: 'Idéal pour les arrivées tardives',
        description: 'Check-in et stationnement plus simples si vous arrivez tard ou repartez tôt.',
        commute: 'Vérifiez le trajet du matin avant de réserver.',
      },
    ],
    stayTypesTitle: "Choisissez le type d'hébergement adapté",
    stayTypesIntro: 'Le bon choix suit votre agenda, pas la plus longue liste de services.',
    stayTypes: [
      {
        title: 'Hôtels',
        badge: 'Le plus simple',
        description: 'Service prévisible, bagagerie, et arrivée facile le jour même.',
        bestFor: 'Séjours courts ou solo',
      },
      {
        title: 'Appart-hôtels',
        badge: "Plus d'espace",
        description: 'Une kitchenette et de la place pour plusieurs nuits.',
        bestFor: 'Équipes et longs séjours',
      },
      {
        title: "Maisons d'hôtes et locations",
        badge: 'Le plus local',
        description: "Plus de charme et de souplesse, avec un peu plus à vérifier sur l'accès.",
        bestFor: 'Séjours prolongés ou en groupe',
      },
    ],
    stayFinder: {
      title: 'Trouvez votre hébergement',
      intro:
        "Choisissez la zone, le type d'hébergement, et les critères pratiques qui comptent pour vous pour affiner la sélection, puis ouvrez un lieu pour explorer plus loin.",
      filters: [
        {
          id: 'zone',
          label: 'Zone',
          options: [
            { id: 'venue-area', label: 'Autour du lieu', searchQuery: zoneSearchQueryById['venue-area'] },
            { id: 'near-stations', label: 'Près des gares', searchQuery: zoneSearchQueryById['near-stations'] },
            { id: 'historic-center', label: 'Centre historique', searchQuery: zoneSearchQueryById['historic-center'] },
          ],
        },
        {
          id: 'type',
          label: 'Type',
          options: [
            { id: 'hotel', label: 'Hôtel', searchQuery: 'hotel' },
            { id: 'aparthotel', label: 'Appart-hôtel', searchQuery: 'appart hotel' },
            { id: 'guesthouse', label: "Maison d'hôtes", searchQuery: 'maison d hotes' },
          ],
        },
        {
          id: 'feature',
          label: 'Équipements',
          options: [{ id: 'parking', label: 'Parking', searchQuery: 'parking' }],
        },
      ],
      resultsLabel: 'hébergements correspondent',
      mapsSearchLabel: 'Voir plus sur Google Maps',
      mapsSearchContextLabel,
      mapsSearchBaseQuery,
      venueMapHref,
      resetLabel: 'Réinitialiser',
      emptyTitle: 'Aucun hébergement ne correspond',
      emptyText: 'Retirez un filtre pour élargir les options.',
      stays: [
        {
          name: 'Odalys City Aix-en-Provence',
          blurb:
            'Studios et appartements équipés près du cours Gambetta, à deux pas du centre des congrès, avec parking sur place.',
          address: '15 cours Gambetta, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Autour du lieu',
          typeId: 'aparthotel',
          typeLabel: 'Appart-hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.odalys-vacances.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.52419', '5.454989'),
        },
        {
          name: 'Hôtel Cardinal',
          blurb:
            'Hôtel de charme au bon rapport qualité-prix, dans deux immeubles du XVIIIe siècle du quartier Mazarin.',
          address: '24 rue Cardinale, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Autour du lieu',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: [],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.hotel-cardinal-aix.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.525482', '5.451718'),
        },
        {
          name: 'Villa Saint-Ange',
          blurb: 'Domaine 5 étoiles à quelques pas du lieu, avec parking couvert et sécurisé.',
          address: '7 traverse Saint-Pierre, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Autour du lieu',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.villasaintange.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.523472', '5.458015'),
        },
        {
          name: 'Hôtel des Arts',
          blurb:
            'Petit hôtel 2 étoiles simple et convivial, à quelques minutes du lieu, du cours Mirabeau et de La Rotonde.',
          address: '3 rue de la Fonderie, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Autour du lieu',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: [],
          websiteLabel: 'Site web',
          websiteHref: 'https://hoteldesarts-aix.fr/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.529323', '5.453524'),
        },
        {
          name: 'Villa Gallici',
          blurb: 'Bastide 5 étoiles Relais & Châteaux avec jardins et parking privé, à courte distance du lieu.',
          address: '18 avenue de la Violette, 13100 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Autour du lieu',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.villagallici.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.536411', '5.448629'),
        },
        {
          name: 'La petite Mazarine',
          blurb:
            "Maison d'hôtes paisible de 2 chambers avec piscine partagée sur les hauteurs, à quelques minutes du centre en voiture.",
          address: '1135 chemin du vallon des lauriers, 13080 Aix-en-Provence',
          zoneId: 'venue-area',
          zoneLabel: 'Autour du lieu',
          typeId: 'guesthouse',
          typeLabel: "Maison d'hôtes",
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.aixenprovencetourism.com/fr/fiche/la-petite-mazarine-7579730',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.545628', '5.471568'),
        },
        {
          name: 'Hôtel Rotonde',
          blurb: 'Hôtel 4 étoiles élégant à côté de La Rotonde et des gares, avec parking privé.',
          address: '15 avenue des Belges, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.hotel-rotonde.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.523677', '5.442665'),
        },
        {
          name: 'Séjours et Affairs Mirabeau',
          blurb: 'Studios et deux-pièces prêts à vivre près des gares, avec parking privé couvert.',
          address: '615 avenue Wolfgang Amadeus Mozart, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'aparthotel',
          typeLabel: 'Appart-hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref:
            'https://www.myresidhome.com/aix-en-provence/sejours-affaires-aix-en-provence-mirabeau/apparthotel-residence-hoteliere.html',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.525363', '5.441426'),
        },
        {
          name: 'Boutique Hôtel Cézanne',
          blurb: 'Boutique-hôtel design à deux pas des gares, avec parking privé sur réservation.',
          address: '40 avenue Victor Hugo, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://boutiquehotelcezanne.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.523353', '5.445922'),
        },
        {
          name: 'Odalys City Aix-en-Provence Centre Rotonde',
          blurb: 'Appart-hôtel 4 étoiles à deux pas de La Rotonde, avec garage souterrain et piscine.',
          address: '24 boulevard Albert Charrier, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'aparthotel',
          typeLabel: 'Appart-hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.odalys-vacances.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.521542', '5.444778'),
        },
        {
          name: 'Hôtel Saint-Christophe',
          blurb: 'Adresse provençale classique près de La Rotonde et des gares, avec garage et parking à proximité.',
          address: '2 avenue Victor Hugo, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.hotel-saintchristophe.fr/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.525508', '5.446202'),
        },
        {
          name: 'Grand Hôtel Roi René - MGallery',
          blurb: 'Hôtel haut de gamme entre les gares et le cours Mirabeau, avec parking privé sur demande.',
          address: '24 boulevard du Roi René, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.grandhotelroirene-aixenprovence.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.523875', '5.449543'),
        },
        {
          name: 'Aparthotel Adagio Aix Centre',
          blurb: 'Appartements tout équipés près de La Rotonde, rénovés en 2025, avec parking privé couvert.',
          address: '3-5 rue des Chartreux, 13100 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'aparthotel',
          typeLabel: 'Appart-hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.adagio-city.com/fr/hotel-6796-aparthotel-adagio-aix-en-provence-centre/index.shtml',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.529232', '5.440832'),
        },
        {
          name: 'Hôtel Le Pigonnet',
          blurb: 'Écrin 5 étoiles avec jardins au sud du centre, parking privé gratuit et accès facile aux gares.',
          address: '5 avenue du Pigonnet, 13090 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.esprit-de-france.com/fr/hotels/hotel-le-pigonnet',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.517891', '5.442081'),
        },
        {
          name: 'Villa des Félibres',
          blurb: "Maison d'hôtes de charme avec piscine et garage, au calme, à pied des gares et du centre.",
          address: '4 avenue Saint-Michel du Pigonnet, 13090 Aix-en-Provence',
          zoneId: 'near-stations',
          zoneLabel: 'Près des gares',
          typeId: 'guesthouse',
          typeLabel: "Maison d'hôtes",
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.aix-villa-felibres.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.516513', '5.441748'),
        },
        {
          name: 'Hôtel des Augustins',
          blurb:
            'Hôtel de charme milieu de gamme dans un ancien couvent, à deux pas du cours Mirabeau en zone piétonne.',
          address: '3 rue de la Masse, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Centre historique',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: [],
          websiteLabel: 'Site web',
          websiteHref: 'https://hotel-augustins.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.526913', '5.44714'),
        },
        {
          name: 'Negrecoste Hôtel & Spa',
          blurb: 'Hôtel 4 étoiles en plein cours Mirabeau, avec spa Nuxe et parking privé sur réservation.',
          address: '33 cours Mirabeau, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Centre historique',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://hotelnegrecoste.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.526768', '5.44896'),
        },
        {
          name: 'Hôtel des Quatre Dauphins',
          blurb:
            'Hôtel cosy dans un hôtel particulier du XIXe siècle à Mazarin, tout près de la fontaine des Quatre Dauphins.',
          address: '54 rue Roux Alphéran, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Centre historique',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: [],
          websiteLabel: 'Site web',
          websiteHref: 'https://lesquatredauphins.fr/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.524955', '5.450308'),
        },
        {
          name: "La Maison d'Aix",
          blurb: "Maison d'hôtes de charme dans un hôtel particulier, au calme dans le quartier Mazarin.",
          address: '25 rue du 4 Septembre, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Centre historique',
          typeId: 'guesthouse',
          typeLabel: "Maison d'hôtes",
          featureIds: [],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.lamaisondaix.com/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.524648', '5.450391'),
        },
        {
          name: 'Aquabella Hôtel & Spa',
          blurb: 'Calme du centre ancien avec jardin et spa sensoriel près des Thermes, parking à proximité.',
          address: '2 rue des Étuves, 13100 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Centre historique',
          typeId: 'hotel',
          typeLabel: 'Hôtel',
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.aquabella.fr/',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.531199', '5.44503'),
        },
        {
          name: 'Villa Hélène',
          blurb:
            "Maison d'hôtes élégante de 5 chambers avec piscine et table d'hôtes, dans la verdure au nord de la ville.",
          address: '920 chemin du Vallon de Bagnol, 13090 Aix-en-Provence',
          zoneId: 'historic-center',
          zoneLabel: 'Centre historique',
          typeId: 'guesthouse',
          typeLabel: "Maison d'hôtes",
          featureIds: ['parking'],
          websiteLabel: 'Site web',
          websiteHref: 'https://www.aixenprovencetourism.com/fr/fiche/villa-helene-7337018',
          mapLabel: 'Carte',
          mapHref: mapsPin('43.544369', '5.434174'),
        },
      ],
    },
    checklistTitle: 'Avant de réserver',
    checklist: [
      'Réservez tôt pour la zone du lieu ou le centre historique.',
      "Vérifiez le temps de marche réel jusqu'au lieu, pas seulement le nom du quartier.",
      "Arrivée tardive ? Confirmez les horaires de check-in et l'accès taxi.",
      'En voiture ? Vérifiez le stationnement avant un hébergement central.',
    ],
    resourcesTitle: 'Liens utiles',
    resources: [
      { text: 'Office de tourisme', href: accommodationResources.tourismOffice },
      { text: 'Plans de la ville', href: accommodationResources.maps },
      { text: 'Site du lieu', href: venueInfo.url ?? 'https://www.aixenprovence-congres.com/en/' },
    ],
    notesTitle: 'Bon à savoir',
  },
} satisfies PracticalInfoTopicData;
